version: "3.9"
services:
  database:
    image: "mongodb"
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$(MONGO_USER)
      - MONGO_INITDB_ROOT_PASSWORD=$(MONGO_PASSWORD)

volumes:
  mongo:
