version: "3.9"
services:
  backend:
    image: "node"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    working_dir: "/app"
    entrypoint:
      - npm
      - run
      - dev
    environment:
      - PORT=3000
    depends_on:
      - database

  database:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  database:
