version: "3.9"
services:
  backend:
    image: "node:alpine"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    working_dir: "/app"
    entrypoint:
      - npm
      - run
      - dev
    environment:
      - PORT=3000

  backendEvents:
    image: "node:alpine"
    ports:
      - "3001:3001"
    volumes:
      - ./backendEvents:/app
    working_dir: "/app"
    entrypoint:
      - npm
      - run
      - dev
    depends_on:
      - databaseEvents
    environment:
      - PORT=3001

  backendUsers:
    image: "node:alpine"
    ports:
      - "3002:3002"
    volumes:
      - ./backendUsers:/app
    working_dir: "/app"
    entrypoint:
      - npm
      - run
      - dev
    depends_on:
      - databaseUser
    environment:
      - PORT=3002

  databaseEvents:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgresEvents:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_USERS_DB}

  databaseUser:
    image: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - postgresUser:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_EVENTS_DB}

volumes:
  postgresUser:
  postgresEvents:
